name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  connectivity_plus: ^7.1.1
  dio: ^5.9.2
  drift: ^2.33.0
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.3.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  go_router: ^17.2.3
  google_fonts: ^8.1.0
  hive_flutter: ^1.1.0
  http: ^1.6.0
  image_picker: ^1.2.2
  permission_handler: ^12.0.2
  riverpod_annotation: ^4.0.2
  speech_to_text: ^7.4.0
  sqlite3_flutter_libs: ^0.6.0+eol
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.4-dev.1
  drift_dev: ^2.33.0
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/shield-mascot.png
    - assets/models/shield-mascot.glb
